CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(120 CHAR) NOT NULL,
    email VARCHAR2(180 CHAR) NOT NULL UNIQUE,
    password VARCHAR2(255 CHAR) NOT NULL,
    role VARCHAR2(20 CHAR) DEFAULT 'USER' NOT NULL
);

CREATE TABLE conversation_sessions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(120 CHAR) NOT NULL,
    source_language VARCHAR2(10 CHAR) NOT NULL,
    target_language VARCHAR2(10 CHAR) NOT NULL,
    status VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    owner_email VARCHAR2(180 CHAR) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE translation_messages (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id NUMBER NOT NULL,
    sender_name VARCHAR2(120 CHAR) NOT NULL,
    source_language VARCHAR2(10 CHAR) NOT NULL,
    target_language VARCHAR2(10 CHAR) NOT NULL,
    original_text VARCHAR2(2000 CHAR) NOT NULL,
    translated_text VARCHAR2(2000 CHAR) NOT NULL,
    audio_url VARCHAR2(512 CHAR),
    delivery_status VARCHAR2(20 CHAR) DEFAULT 'DELIVERED' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_translation_session
        FOREIGN KEY (session_id)
        REFERENCES conversation_sessions(id)
);

CREATE INDEX idx_sessions_owner_email ON conversation_sessions(owner_email);
CREATE INDEX idx_messages_session_id ON translation_messages(session_id);
